### ISSUE TITLE
how to update to 0.10?

### ISSUE THREAD

**Issue by moebiussurfing** [trentbrooks/ofxTouchGUI#1]
I am getting xml related errors:
```
/Users/x/Documents/openFrameworks/addons/ofxTouchGUI/src/ofxTouchGUI.mm:1011:9: No member named 'setTo' in 'ofXml'
/Users/x/Documents/openFrameworks/addons/ofxTouchGUI/src/ofxTouchGUI.mm:1012:28: No member named 'getNumChildren' in 'ofXml'
/Users/x/Documents/openFrameworks/addons/ofxTouchGUI/src/ofxTouchGUI.mm:1016:13: No member named 'setToChild' in 'ofXml'
```
Should we use oxPoco like happens in some other addons? I tried this without success.
is this plugin still recommended or you are using other addons like ofxRemoteUI?

**Comment by trentbrooks** [comment]
Hey - yeah the addons required to work with of 0.1 are now: ofxTouchGUI, ofxPoco, and ofxOsc. I just pushed an example to a new branch here: https://github.com/trentbrooks/ofxTouchGUI/tree/of_010
